### ISSUE TITLE
Search pattern never detected in send_command_expect

### ISSUE THREAD

**Issue by roshanraj30** [nornir-automation/nornir_napalm#12]
I'm new to Nornir. I'm trying to grab "get_facts" from multiple telnet devices. Most of the devices return results as expected. I'm just facing issue for a couple of devices (C4510 - IOS-XE 03.02.05.SG & C2960 - 15.2(4)E6). I'm receiving below error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/napalm/ios/ios.py", line 204, in _send_command
    output = self.device.send_command(command)
  File "/usr/local/lib/python3.6/site-packages/netmiko/utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1431, in send_command
    search_pattern
OSError: Search pattern never detected in send_command_expect: LO\-CO\-EXT\-SW1\#

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 44, in napalm_get
    result[g] = method(**options)
  File "/usr/local/lib/python3.6/site-packages/napalm/ios/ios.py", line 970, in get_facts
    show_ver = self._send_command("show version")
  File "/usr/local/lib/python3.6/site-packages/napalm/ios/ios.py", line 207, in _send_command
    raise ConnectionClosedException(str(e))
napalm.base.exceptions.ConnectionClosedException: Search pattern never detected in send_command_expect: LO\-CO\-EXT\-SW1\#
```

I tried adding 'global_delay_factor' to the optional_args but anything greater than 3 changes the error to below:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/napalm/ios/ios.py", line 204, in _send_command
    output = self.device.send_command(command)
  File "/usr/local/lib/python3.6/site-packages/netmiko/utilities.py", line 347, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 1427, in send_command
    new_data = self.read_channel()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 503, in read_channel
    output = self._read_channel()
  File "/usr/local/lib/python3.6/site-packages/netmiko/base_connection.py", line 485, in _read_channel
    output = self.remote_conn.read_very_eager().decode("utf-8", "ignore")
  File "/usr/lib64/python3.6/telnetlib.py", line 366, in read_very_eager
    return self.read_very_lazy()
  File "/usr/lib64/python3.6/telnetlib.py", line 403, in read_very_lazy
    raise EOFError('telnet connection closed')
EOFError: telnet connection closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/site-packages/nornir_napalm/plugins/tasks/napalm_get.py", line 44, in napalm_get
    result[g] = method(**options)
  File "/usr/local/lib/python3.6/site-packages/napalm/ios/ios.py", line 970, in get_facts
    show_ver = self._send_command("show version")
  File "/usr/local/lib/python3.6/site-packages/napalm/ios/ios.py", line 207, in _send_command
    raise ConnectionClosedException(str(e))
napalm.base.exceptions.ConnectionClosedException: telnet connection closed
```
Below are the connection_options I'm using for NAPALM:

```
napalm:
  platform: ios
  extras:
    optional_args:
      transport: telnet
      secret: 'secretkey'
      global_delay_factor: 3
```

**Comment by ktbyers** [comment]
Probably set:

```
fast_cli: False
```

And eliminate the `global_delay_factor`. I would start with that and see what happens.

If that doesn't work, I would keep fast_cli=False and try global_delay_factor=2 and then =4.

**Comment by roshanraj30** [comment]
I tried the above recommendation but unfortunately it still returns the same exception.

**Comment by ktbyers** [comment]
Can you reproduce the issue in straight Netmiko (no Nornir and no NAPALM)? It looks like it is just failing on a "show version" command using Netmiko.

**Comment by roshanraj30** [comment]
Sorry for the delay in response, I found out it was due to terminal length & width commands failing due to AAA authorization.

**Comment by Simperdy** [comment]
@roshanraj30 so what was your solution? I have the same issue for two 2960X switches. Did you changed something in nornir or on the switches?
