### ISSUE TITLE
Very slow device (Cisco IOS) fails to return diff on a configuration dry run

### ISSUE THREAD

**Issue by gaffar10** [nornir-automation/nornir_napalm#15]
Hello, Can someone please help to fix the below issue?

I am trying to push the configuration from the .txt file to the cisco devices using the napalm_configure plugin. However, I am getting the error message "Subtask: napalm_configure (failed)".  I assume the config file, host file, defaults file, group files are good because I can run the other scripts.

The following plugins are installed on my machine.
nornir==3.0.0
nornir-jinja2==0.1.0
nornir-napalm==0.1.1
nornir-netmiko==0.1.1
nornir-scrapli==2020.11.1
nornir-utils==0.1.1

+++++++++++++++Script++++++++++

```python
from nornir import InitNornir
from nornir_napalm.plugins.tasks import napalm_configure
from nornir_utils.plugins.functions import print_result

nr = InitNornir(config_file="config.yaml", dry_run=True)

def dryrun(task):
    task.run(task=napalm_configure, filename="configuration_file.txt")   

results = nr.run(task=dryrun)
print_result(results)
```

++++++++Error Traceback++++++++
Subtask: napalm_configure (failed)

---- napalm_configure ** changed : False --------------------------------------- ERROR
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nornir/core/task.py", line 98, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.8/dist-packages/nornir_napalm/plugins/tasks/napalm_configure.py", line 35, in napalm_configure
    diff = device.compare_config()
  File "/usr/local/lib/python3.8/dist-packages/napalm/ios/ios.py", line 429, in compare_config
    diff = self.device.send_command_expect(cmd)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1576, in send_command_expect
    return self.send_command(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/utilities.py", line 430, in wrapper_decorator
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/netmiko/base_connection.py", line 1529, in send_command
    raise IOError(
OSError: Search pattern never detected in send_command: SW2\#

**Comment by gaffar10** [comment]
Hi Kirk, Thank you very much for your help and for the time. It doesn't work well with the Vios router, let me try with dynamips or with a real router. Thanks again.
